name: govulncheck
run-name: ${{ github.actor }} is testing govulncheck action
on: [push, workflow_dispatch]
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/govulncheck
        with:
          work-dir: ./go/vuln
          repo-checkout: true
