name: govulncheck
run-name: ${{ github.actor }} is testing govulncheck action
on: [push, workflow_dispatch]
jobs:
  govulncheck_job:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/govulncheck
        with:
          #work-dir: ./go/vuln
          repo-checkout: false
          go-version-file: go.mod
          output-format: sarif
          output-file: out.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: out.sarif
            #checkout_path: ./go/vuln
