name: govulncheck
run-name: ${{ github.actor }} is testing govulncheck action
on: [push]
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/govulncheck-action
